services:
  - type: web
    name: rovo-helpdesk-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rovo-db
          property: connectionString
      - key: SLACK_BOT_TOKEN
        value: your-bot-token
      - key: SLACK_SIGNING_SECRET
        value: your-signing-secret
      - key: ROVO_API_KEY
        value: your-rovo-api-key
      - key: ADMIN_EMAIL
        value: your-email@example.com
      - key: SMTP_USER
        value: your-smtp-user
      - key: SMTP_PASS
        value: your-smtp-pass
      - key: SMTP_HOST
        value: smtp.example.com
      - key: SMTP_PORT
        value: "587"
databases:
  - name: rovo-db
    plan: free
